# Generated by Django 6.0.2 on 2026-02-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinemaster',
            name='pharmacology_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='pharmaseed_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
