# Generated by Django 6.0.2 on 2026-02-28 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='reversed_by',
            field=models.ForeignKey(blank=True, help_text='The entry that reversed this one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses_entry', to='accounting.journalentry'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='is_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_books_date', models.DateField(blank=True, help_text='No journal entries can be posted on or before this date.', null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_settings', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statement_date', models.DateField()),
                ('statement_ending_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_completed', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='accounting.bankaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_lines', to='accounting.bankreconciliation'),
        ),
    ]
