# Generated by Django 6.0.2 on 2026-04-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_reversed_by_journalentryline_is_cleared_and_more'),
        ('core', '0005_organization_kiosk_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.UUIDField(db_index=True)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('raw_text', models.TextField(blank=True, help_text='Original CSV row for audit')),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('IGNORED', 'Ignored')], default='UNMATCHED', max_length=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='accounting.bankaccount')),
                ('matched_journal_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_match', to='accounting.journalentryline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='core.organization')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
    ]
