# Generated by Django 6.0.2 on 2026-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_monthly_appointments',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited (enforcement deferred)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_patients',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='limit_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
