# Generated by Django 6.0.2 on 2026-02-28 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_reversed_by_journalentryline_is_cleared_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_ap_account', models.ForeignKey(blank=True, help_text='Default liability account for Accounts Payable (A/P)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('default_ar_account', models.ForeignKey(blank=True, help_text='Default asset account for Accounts Receivable (A/R)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('default_inventory_account', models.ForeignKey(blank=True, help_text='Default asset account for Inventory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('default_revenue_account', models.ForeignKey(blank=True, help_text='Default income account for Sales Revenue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounting.account')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
