# Generated by Django 6.0.2 on 2026-04-07 09:44

import core.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_organization_kiosk_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_booking_enabled', models.BooleanField(default=True)),
                ('slot_duration_mins', models.PositiveIntegerField(default=30)),
                ('working_days', models.JSONField(default=core.models._default_working_days, help_text='List of 3-letter day codes: MON, TUE, WED, THU, FRI, SAT, SUN')),
                ('start_time', models.TimeField(default=datetime.time(9, 0))),
                ('end_time', models.TimeField(default=datetime.time(18, 0))),
                ('advance_booking_days', models.PositiveIntegerField(default=30, help_text='How many days ahead patients can book')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_settings', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
