# Generated by Django 6.0.2 on 2026-04-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bookingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='default_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
