# Generated by Django 6.0.2 on 2026-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequisition',
            name='requisition_type',
            field=models.CharField(choices=[('CLINICAL', 'Clinical (Procedure)'), ('GENERAL', 'General (Clinic)')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='is_clinic_item',
            field=models.BooleanField(default=False, help_text='Can be requested via General Requisitions (Inventory Page)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_procedure_item',
            field=models.BooleanField(default=False, help_text='Can be requested via Clinical Requisitions (Session Page)'),
        ),
    ]
