# Generated by Django 6.0.2 on 2026-04-07 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_proceduresession_consumable_cost'),
        ('inventory', '0003_purchaseorder_grn_purchaseorderline_grnline_vendor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrequisition',
            name='clinical_reference_id',
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='rejection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_requisitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryrequisition',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='clinical.proceduresession'),
        ),
    ]
