# Generated by Django 6.0.2 on 2026-02-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalintake',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
    ]
