# Generated by Django 6.0.2 on 2026-02-25 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresession',
            name='clinical_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='clinical.clinicalphoto'),
        ),
        migrations.AddField(
            model_name='proceduresession',
            name='consent_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='clinical.consentform'),
        ),
    ]
