# Generated by Django 6.0.2 on 2026-02-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_proceduresession_clinical_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresession',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proceduresession',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
