# Generated by Django 6.0.2 on 2026-02-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_proceduresession_notes_proceduresession_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresession',
            name='specialized_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
