# Generated by Django 6.0.2 on 2026-04-06 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_proceduresession_specialized_data'),
        ('core', '0004_clinicstaff_is_org_admin_organization_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalphoto',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='clinicalphoto',
            name='category',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('PRE_SESSION', 'Pre-Session'), ('POST_SESSION', 'Post-Session')], default='PRE_SESSION', max_length=20),
        ),
        migrations.AddField(
            model_name='clinicalphoto',
            name='photo',
            field=models.ImageField(blank=True, upload_to='clinical/photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='clinicalphoto',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalphoto',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos_taken', to='core.clinicstaff'),
        ),
        migrations.AddField(
            model_name='consentform',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='clinical/signatures/%Y/%m/'),
        ),
    ]
