# Generated by Django 6.0.2 on 2026-04-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_remove_clinicalphoto_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceduresession',
            name='consumable_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
