# Generated by Django 6.0.2 on 2026-04-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_protect_records'),
        ('core', '0006_bookingsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('organization', 'provider', 'date_time')},
        ),
    ]
