# Generated by Django 6.0.2 on 2026-04-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0010_appointment_unique_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='fee_waiver_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee_waiver_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='fee_waiver_requested',
            field=models.BooleanField(default=False),
        ),
    ]
