# Generated by Django 6.0.2 on 2026-04-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0011_appointment_fee_waiver_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionmedication',
            name='recommendations',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescriptionmedication',
            name='dose',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
