# Generated by Django 6.0.2 on 2026-04-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0012_prescriptionmedication_recommendations_dose_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
