# Generated by Django 6.0.2 on 2026-04-14 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0013_arrived_at_field'),
        ('inventory', '0004_remove_inventoryrequisition_clinical_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_as', to='inventory.product'),
        ),
    ]
