# Generated by Django 6.0.2 on 2026-02-24 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('target', models.CharField(choices=[('FEE', 'Consultation Fee'), ('PROCEDURE', 'Procedure'), ('PACKAGE', 'Package'), ('PRODUCT', 'Product')], max_length=20)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'Percentage (%)'), ('AMOUNT', 'Fixed Amount ($)'), ('NONE', 'No Discount')], default='PERCENT', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_consumed', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('max_usages_per_patient', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
